fn main() {
    let out = std::env::var("OUT_DIR").unwrap();
    let out_dir = format!("{out}/protos");

    std::fs::create_dir_all(&out_dir).unwrap();

    protobuf_codegen::Codegen::new()
        .pure()
        .out_dir(out_dir)
        .inputs(["protos/message.proto"])
        .include("protos")
        .customize(protobuf_codegen::Customize::default().tokio_bytes(true))
        .run()
        .expect("Codegen failed.");

    builtin_defaults(&out);
}

/// Bakes the server defaults into the binary (docs/server-config-provisioning.md §2).
/// Each value comes from an environment variable at build time and is empty when
/// the variable is unset, so a developer build carries no defaults. The real values
/// live only in the build environment (CI secrets, the local env file), never in the
/// repository.
fn builtin_defaults(out: &str) {
    const VARS: [(&str, &str); 4] = [
        ("BUILTIN_ID_SERVER", "OPENUU_DEFAULT_ID_SERVER"),
        ("BUILTIN_RELAY_SERVER", "OPENUU_DEFAULT_RELAY_SERVER"),
        ("BUILTIN_API_SERVER", "OPENUU_DEFAULT_API_SERVER"),
        ("BUILTIN_KEY", "OPENUU_DEFAULT_KEY"),
    ];
    let mut src = String::from("// Generated by libs/base/build.rs; do not edit.\n");
    for (name, var) in VARS {
        println!("cargo:rerun-if-env-changed={var}");
        let value = std::env::var(var).unwrap_or_default();
        let value = value.trim();
        src.push_str(&format!("pub const {name}: &str = {value:?};\n"));
    }
    std::fs::write(format!("{out}/builtin_defaults.rs"), src).unwrap();
}
