//! Option keys shared across the app.
//!
//! The handful that `hbb_common` itself reads stay defined there and are
//! re-exported here, so callers always use this one path.

pub use hbb_common::config::keys::*;

mod options;
pub use options::*;
mod builtin;
pub use builtin::*;
mod connection;
pub use connection::*;
mod local;
pub use local::*;

// DEFAULT_DISPLAY_SETTINGS, OVERWRITE_DISPLAY_SETTINGS
pub const KEYS_DISPLAY_SETTINGS: &[&str] = &[
    OPTION_VIEW_ONLY,
    OPTION_SHOW_MONITORS_TOOLBAR,
    OPTION_COLLAPSE_TOOLBAR,
    OPTION_SHOW_REMOTE_CURSOR,
    OPTION_FOLLOW_REMOTE_CURSOR,
    OPTION_FOLLOW_REMOTE_WINDOW,
    OPTION_ZOOM_CURSOR,
    OPTION_SHOW_QUALITY_MONITOR,
    OPTION_DISABLE_AUDIO,
    OPTION_ENABLE_FILE_COPY_PASTE,
    OPTION_DISABLE_CLIPBOARD,
    OPTION_LOCK_AFTER_SESSION_END,
    OPTION_PRIVACY_MODE,
    OPTION_TOUCH_MODE,
    OPTION_I444,
    OPTION_REVERSE_MOUSE_WHEEL,
    OPTION_SWAP_LEFT_RIGHT_MOUSE,
    OPTION_DISPLAYS_AS_INDIVIDUAL_WINDOWS,
    OPTION_USE_ALL_MY_DISPLAYS_FOR_THE_REMOTE_SESSION,
    OPTION_VIEW_STYLE,
    OPTION_TERMINAL_PERSISTENT,
    OPTION_SCROLL_STYLE,
    OPTION_EDGE_SCROLL_EDGE_THICKNESS,
    OPTION_IMAGE_QUALITY,
    OPTION_CUSTOM_IMAGE_QUALITY,
    OPTION_CUSTOM_FPS,
    OPTION_CODEC_PREFERENCE,
    OPTION_SYNC_INIT_CLIPBOARD,
    OPTION_TRACKPAD_SPEED,
];
// DEFAULT_LOCAL_SETTINGS, OVERWRITE_LOCAL_SETTINGS
pub const KEYS_LOCAL_SETTINGS: &[&str] = &[
    OPTION_THEME,
    OPTION_LANGUAGE,
    OPTION_ENABLE_CONFIRM_CLOSING_TABS,
    OPTION_ENABLE_OPEN_NEW_CONNECTIONS_IN_TABS,
    OPTION_TEXTURE_RENDER,
    OPTION_ALLOW_D3D_RENDER,
    OPTION_SYNC_AB_WITH_RECENT_SESSIONS,
    OPTION_SYNC_AB_TAGS,
    OPTION_FILTER_AB_BY_INTERSECTION,
    OPTION_REMOTE_MENUBAR_DRAG_LEFT,
    OPTION_REMOTE_MENUBAR_DRAG_RIGHT,
    OPTION_HIDE_AB_TAGS_PANEL,
    OPTION_FLUTTER_REMOTE_MENUBAR_STATE,
    OPTION_FLUTTER_PEER_SORTING,
    OPTION_FLUTTER_PEER_TAB_INDEX,
    OPTION_FLUTTER_PEER_TAB_ORDER,
    OPTION_FLUTTER_PEER_TAB_VISIBLE,
    OPTION_FLUTTER_PEER_CARD_UI_TYLE,
    OPTION_FLUTTER_CURRENT_AB_NAME,
    OPTION_DISABLE_FLOATING_WINDOW,
    OPTION_FLOATING_WINDOW_SIZE,
    OPTION_FLOATING_WINDOW_UNTOUCHABLE,
    OPTION_FLOATING_WINDOW_TRANSPARENCY,
    OPTION_FLOATING_WINDOW_SVG,
    OPTION_KEEP_SCREEN_ON,
    // Client-side: keep client system awake during outgoing sessions (General setting)
    OPTION_KEEP_AWAKE_DURING_OUTGOING_SESSIONS,
    OPTION_DISABLE_GROUP_PANEL,
    OPTION_DISABLE_DISCOVERY_PANEL,
    OPTION_PRE_ELEVATE_SERVICE,
    OPTION_ALLOW_REMOTE_CM_MODIFICATION,
    OPTION_ALLOW_SYNC_CLIPBOARD_BETWEEN_SESSIONS,
    OPTION_ENABLE_CHECK_UPDATE,
    OPTION_ALLOW_AUTO_RECORD_OUTGOING,
    OPTION_HIDE_RECORDING_BUTTON,
    OPTION_VIDEO_SAVE_DIRECTORY,
    OPTION_ENABLE_TCP_PUNCH,
    OPTION_ENABLE_UDP_PUNCH,
    OPTION_ENABLE_IPV6_PUNCH,
    OPTION_ENABLE_PORT_FORWARD_MUX,
    OPTION_ENABLE_WEBRTC,
    OPTION_TOUCH_MODE,
    OPTION_SHOW_VIRTUAL_MOUSE,
    OPTION_SHOW_VIRTUAL_JOYSTICK,
    OPTION_ENABLE_FLUTTER_HTTP_ON_RUST,
    OPTION_ALLOW_ASK_FOR_NOTE,
];
// DEFAULT_SETTINGS, OVERWRITE_SETTINGS
pub const KEYS_SETTINGS: &[&str] = &[
    OPTION_ACCESS_MODE,
    OPTION_ENABLE_KEYBOARD,
    OPTION_ENABLE_CLIPBOARD,
    OPTION_ENABLE_FILE_TRANSFER,
    OPTION_ENABLE_CAMERA,
    OPTION_ENABLE_TERMINAL,
    OPTION_ENABLE_AUDIO,
    OPTION_ENABLE_TUNNEL,
    OPTION_ENABLE_REMOTE_RESTART,
    OPTION_ENABLE_RECORD_SESSION,
    OPTION_ENABLE_BLOCK_INPUT,
    OPTION_ENABLE_PRIVACY_MODE,
    OPTION_ALLOW_SCOPE_VIOLATION_CLOSE,
    OPTION_ALLOW_SCOPE_VIOLATION_ALARM,
    OPTION_ALLOW_REMOTE_CONFIG_MODIFICATION,
    OPTION_ALLOW_NUMERNIC_ONE_TIME_PASSWORD,
    OPTION_ENABLE_LAN_DISCOVERY,
    OPTION_DIRECT_SERVER,
    OPTION_DIRECT_ACCESS_PORT,
    OPTION_WHITELIST,
    OPTION_ID_WHITELIST,
    OPTION_ALLOW_AUTO_DISCONNECT,
    OPTION_AUTO_DISCONNECT_TIMEOUT,
    OPTION_ALLOW_ONLY_CONN_WINDOW_OPEN,
    OPTION_ALLOW_AUTO_RECORD_INCOMING,
    OPTION_WINDOWS_SERVICE_VIDEO_SAVE_DIRECTORY,
    OPTION_ENABLE_ABR,
    OPTION_ALLOW_REMOVE_WALLPAPER,
    OPTION_ALLOW_ALWAYS_SOFTWARE_RENDER,
    OPTION_ENABLE_HWCODEC,
    OPTION_APPROVE_MODE,
    OPTION_VERIFICATION_METHOD,
    OPTION_TEMPORARY_PASSWORD_LENGTH,
    OPTION_PROXY_URL,
    OPTION_PROXY_USERNAME,
    OPTION_PROXY_PASSWORD,
    OPTION_CUSTOM_RENDEZVOUS_SERVER,
    OPTION_API_SERVER,
    OPTION_KEY,
    OPTION_ALLOW_WEBSOCKET,
    OPTION_PRESET_ADDRESS_BOOK_NAME,
    OPTION_PRESET_ADDRESS_BOOK_TAG,
    OPTION_PRESET_ADDRESS_BOOK_ALIAS,
    OPTION_PRESET_ADDRESS_BOOK_PASSWORD,
    OPTION_PRESET_ADDRESS_BOOK_NOTE,
    OPTION_PRESET_DEVICE_USERNAME,
    OPTION_PRESET_DEVICE_NAME,
    OPTION_PRESET_NOTE,
    OPTION_ENABLE_DIRECTX_CAPTURE,
    OPTION_ENABLE_ANDROID_SOFTWARE_ENCODING_HALF_SCALE,
    OPTION_ENABLE_TRUSTED_DEVICES,
    OPTION_RELAY_SERVER,
    OPTION_ICE_SERVERS,
    OPTION_DISABLE_UDP,
    OPTION_ALLOW_INSECURE_TLS_FALLBACK,
    OPTION_KEEP_AWAKE_DURING_INCOMING_SESSIONS,
    OPTION_ALLOW_AUTO_UPDATE,
    OPTION_ALLOW_KCP_CC,
    OPTION_ALLOW_WEBRTC_CC,
];

// BUILDIN_SETTINGS
pub const KEYS_BUILDIN_SETTINGS: &[&str] = &[
    OPTION_DISPLAY_NAME,
    OPTION_AVATAR,
    OPTION_PRESET_DEVICE_GROUP_NAME,
    OPTION_PRESET_USERNAME,
    OPTION_PRESET_STRATEGY_NAME,
    OPTION_REMOVE_PRESET_PASSWORD_WARNING,
    OPTION_HIDE_GENERAL_SETTINGS,
    OPTION_HIDE_SECURITY_SETTINGS,
    OPTION_HIDE_NETWORK_SETTINGS,
    OPTION_HIDE_SERVER_SETTINGS,
    OPTION_HIDE_PROXY_SETTINGS,
    OPTION_HIDE_WEBSOCKET_SETTINGS,
    OPTION_HIDE_STOP_SERVICE,
    OPTION_HIDE_USERNAME_ON_CARD,
    OPTION_HIDE_HELP_CARDS,
    OPTION_DEFAULT_CONNECT_PASSWORD,
    OPTION_HIDE_TRAY,
    OPTION_ONE_WAY_CLIPBOARD_REDIRECTION,
    OPTION_ALLOW_LOGON_SCREEN_PASSWORD,
    OPTION_ALLOW_DEEP_LINK_PASSWORD,
    OPTION_ALLOW_DEEP_LINK_SERVER_SETTINGS,
    OPTION_ONE_WAY_FILE_TRANSFER,
    OPTION_ALLOW_HTTPS_21114,
    OPTION_ALLOW_HOSTNAME_AS_ID,
    OPTION_REGISTER_DEVICE,
    OPTION_HIDE_POWERED_BY_ME,
    OPTION_MAIN_WINDOW_ALWAYS_ON_TOP,
    OPTION_FILE_TRANSFER_MAX_FILES,
    OPTION_DISABLE_CHANGE_PERMANENT_PASSWORD,
    OPTION_DISABLE_CHANGE_ID,
    OPTION_DISABLE_UNLOCK_PIN,
    OPTION_USE_RAW_TCP_FOR_API,
    OPTION_ENABLE_PERM_CHANGE_IN_ACCEPT_WINDOW,
    OPTION_ALLOW_COMMAND_LINE_SETTINGS_WHEN_SETTINGS_DISABLED,
];

#[cfg(test)]
mod tests {
    /// The glob above and the constants below share one namespace, and Rust
    /// silently prefers the explicit item over a glob import. A key defined on
    /// both sides would therefore compile, with the client and the server
    /// disagreeing about its string value and nothing to signal it. Keep the
    /// two sets apart.
    #[test]
    fn key_names_do_not_collide_with_hbb_common() {
        fn names(src: &str) -> Vec<&str> {
            src.lines()
                .filter_map(|l| l.trim().strip_prefix("pub const "))
                .filter_map(|l| l.split(':').next())
                .map(str::trim)
                .filter(|n| n.starts_with("OPTION_") || n.starts_with("KEYS_"))
                .collect()
        }

        // every topic file of this module, so a key defined anywhere in it is seen
        let here = names(concat!(
            include_str!("options.rs"),
            include_str!("builtin.rs"),
            include_str!("connection.rs"),
            include_str!("local.rs"),
            include_str!("display_settings.rs"),
            include_str!("local_settings.rs"),
            include_str!("settings.rs"),
            include_str!("buildin_settings.rs"),
        ));
        let there = names(include_str!("../../../../hbb_common/src/config.rs"));
        assert!(
            !here.is_empty() && !there.is_empty(),
            "key parsing found nothing"
        );

        let both: Vec<_> = here.iter().filter(|n| there.contains(n)).collect();
        assert!(
            both.is_empty(),
            "defined in both crates, so the local one shadows hbb_common's \
             with no diagnostic: {:?}",
            both
        );
    }
}
