use super::*;

lazy_static::lazy_static! {
pub(super) static ref KEY_MAP: HashMap<enigo::Key, evdev::Key> = HashMap::from(
    [
        (enigo::Key::Alt, evdev::Key::KEY_LEFTALT),
        (enigo::Key::Backspace, evdev::Key::KEY_BACKSPACE),
        (enigo::Key::CapsLock, evdev::Key::KEY_CAPSLOCK),
        (enigo::Key::Control, evdev::Key::KEY_LEFTCTRL),
        (enigo::Key::Delete, evdev::Key::KEY_DELETE),
        (enigo::Key::DownArrow, evdev::Key::KEY_DOWN),
        (enigo::Key::End, evdev::Key::KEY_END),
        (enigo::Key::Escape, evdev::Key::KEY_ESC),
        (enigo::Key::F1, evdev::Key::KEY_F1),
        (enigo::Key::F10, evdev::Key::KEY_F10),
        (enigo::Key::F11, evdev::Key::KEY_F11),
        (enigo::Key::F12, evdev::Key::KEY_F12),
        (enigo::Key::F2, evdev::Key::KEY_F2),
        (enigo::Key::F3, evdev::Key::KEY_F3),
        (enigo::Key::F4, evdev::Key::KEY_F4),
        (enigo::Key::F5, evdev::Key::KEY_F5),
        (enigo::Key::F6, evdev::Key::KEY_F6),
        (enigo::Key::F7, evdev::Key::KEY_F7),
        (enigo::Key::F8, evdev::Key::KEY_F8),
        (enigo::Key::F9, evdev::Key::KEY_F9),
        (enigo::Key::Home, evdev::Key::KEY_HOME),
        (enigo::Key::LeftArrow, evdev::Key::KEY_LEFT),
        (enigo::Key::Meta, evdev::Key::KEY_LEFTMETA),
        (enigo::Key::Option, evdev::Key::KEY_OPTION),
        (enigo::Key::PageDown, evdev::Key::KEY_PAGEDOWN),
        (enigo::Key::PageUp, evdev::Key::KEY_PAGEUP),
        (enigo::Key::Return, evdev::Key::KEY_ENTER),
        (enigo::Key::RightArrow, evdev::Key::KEY_RIGHT),
        (enigo::Key::Shift, evdev::Key::KEY_LEFTSHIFT),
        (enigo::Key::Space, evdev::Key::KEY_SPACE),
        (enigo::Key::Tab, evdev::Key::KEY_TAB),
        (enigo::Key::UpArrow, evdev::Key::KEY_UP),
        (enigo::Key::Numpad0, evdev::Key::KEY_KP0),  // check if correct?
        (enigo::Key::Numpad1, evdev::Key::KEY_KP1),
        (enigo::Key::Numpad2, evdev::Key::KEY_KP2),
        (enigo::Key::Numpad3, evdev::Key::KEY_KP3),
        (enigo::Key::Numpad4, evdev::Key::KEY_KP4),
        (enigo::Key::Numpad5, evdev::Key::KEY_KP5),
        (enigo::Key::Numpad6, evdev::Key::KEY_KP6),
        (enigo::Key::Numpad7, evdev::Key::KEY_KP7),
        (enigo::Key::Numpad8, evdev::Key::KEY_KP8),
        (enigo::Key::Numpad9, evdev::Key::KEY_KP9),
        (enigo::Key::Cancel, evdev::Key::KEY_CANCEL),
        (enigo::Key::Clear, evdev::Key::KEY_CLEAR),
        (enigo::Key::Alt, evdev::Key::KEY_LEFTALT),
        (enigo::Key::Pause, evdev::Key::KEY_PAUSE),
        (enigo::Key::Kana, evdev::Key::KEY_KATAKANA),  // check if correct?
        (enigo::Key::Hangul, evdev::Key::KEY_HANGEUL),  // check if correct?
        // (enigo::Key::Junja, evdev::Key::KEY_JUNJA),     // map?
        // (enigo::Key::Final, evdev::Key::KEY_FINAL),     // map?
        (enigo::Key::Hanja, evdev::Key::KEY_HANJA),
        // (enigo::Key::Kanji, evdev::Key::KEY_KANJI),      // map?
        // (enigo::Key::Convert, evdev::Key::KEY_CONVERT),
        (enigo::Key::Select, evdev::Key::KEY_SELECT),
        (enigo::Key::Print, evdev::Key::KEY_PRINT),
        // (enigo::Key::Execute, evdev::Key::KEY_EXECUTE),
        (enigo::Key::Snapshot, evdev::Key::KEY_SYSRQ),
        (enigo::Key::Insert, evdev::Key::KEY_INSERT),
        (enigo::Key::Help, evdev::Key::KEY_HELP),
        (enigo::Key::Sleep, evdev::Key::KEY_SLEEP),
        // (enigo::Key::Separator, evdev::Key::KEY_SEPARATOR),
        (enigo::Key::Scroll, evdev::Key::KEY_SCROLLLOCK),
        (enigo::Key::NumLock, evdev::Key::KEY_NUMLOCK),
        (enigo::Key::RWin, evdev::Key::KEY_RIGHTMETA),
        (enigo::Key::Apps, evdev::Key::KEY_COMPOSE),    // it's a little strange that the key is mapped to KEY_COMPOSE, not KEY_MENU
        (enigo::Key::Multiply, evdev::Key::KEY_KPASTERISK),
        (enigo::Key::Add, evdev::Key::KEY_KPPLUS),
        (enigo::Key::Subtract, evdev::Key::KEY_KPMINUS),
        (enigo::Key::Decimal, evdev::Key::KEY_KPCOMMA),   // KEY_KPDOT and KEY_KPCOMMA are exchanged?
        (enigo::Key::Divide, evdev::Key::KEY_KPSLASH),
        (enigo::Key::Equals, evdev::Key::KEY_KPEQUAL),
        (enigo::Key::NumpadEnter, evdev::Key::KEY_KPENTER),
        (enigo::Key::RightAlt, evdev::Key::KEY_RIGHTALT),
        (enigo::Key::RightControl, evdev::Key::KEY_RIGHTCTRL),
        (enigo::Key::RightShift, evdev::Key::KEY_RIGHTSHIFT),
    ]);

    pub(super) static ref KEY_MAP_LAYOUT: HashMap<char, (evdev::Key, bool)> = HashMap::from(
        [
            ('a', (evdev::Key::KEY_A, false)),
            ('b', (evdev::Key::KEY_B, false)),
            ('c', (evdev::Key::KEY_C, false)),
            ('d', (evdev::Key::KEY_D, false)),
            ('e', (evdev::Key::KEY_E, false)),
            ('f', (evdev::Key::KEY_F, false)),
            ('g', (evdev::Key::KEY_G, false)),
            ('h', (evdev::Key::KEY_H, false)),
            ('i', (evdev::Key::KEY_I, false)),
            ('j', (evdev::Key::KEY_J, false)),
            ('k', (evdev::Key::KEY_K, false)),
            ('l', (evdev::Key::KEY_L, false)),
            ('m', (evdev::Key::KEY_M, false)),
            ('n', (evdev::Key::KEY_N, false)),
            ('o', (evdev::Key::KEY_O, false)),
            ('p', (evdev::Key::KEY_P, false)),
            ('q', (evdev::Key::KEY_Q, false)),
            ('r', (evdev::Key::KEY_R, false)),
            ('s', (evdev::Key::KEY_S, false)),
            ('t', (evdev::Key::KEY_T, false)),
            ('u', (evdev::Key::KEY_U, false)),
            ('v', (evdev::Key::KEY_V, false)),
            ('w', (evdev::Key::KEY_W, false)),
            ('x', (evdev::Key::KEY_X, false)),
            ('y', (evdev::Key::KEY_Y, false)),
            ('z', (evdev::Key::KEY_Z, false)),
            ('0', (evdev::Key::KEY_0, false)),
            ('1', (evdev::Key::KEY_1, false)),
            ('2', (evdev::Key::KEY_2, false)),
            ('3', (evdev::Key::KEY_3, false)),
            ('4', (evdev::Key::KEY_4, false)),
            ('5', (evdev::Key::KEY_5, false)),
            ('6', (evdev::Key::KEY_6, false)),
            ('7', (evdev::Key::KEY_7, false)),
            ('8', (evdev::Key::KEY_8, false)),
            ('9', (evdev::Key::KEY_9, false)),
            ('`', (evdev::Key::KEY_GRAVE, false)),
            ('-', (evdev::Key::KEY_MINUS, false)),
            ('=', (evdev::Key::KEY_EQUAL, false)),
            ('[', (evdev::Key::KEY_LEFTBRACE, false)),
            (']', (evdev::Key::KEY_RIGHTBRACE, false)),
            ('\\', (evdev::Key::KEY_BACKSLASH, false)),
            (',', (evdev::Key::KEY_COMMA, false)),
            ('.', (evdev::Key::KEY_DOT, false)),
            ('/', (evdev::Key::KEY_SLASH, false)),
            (';', (evdev::Key::KEY_SEMICOLON, false)),
            ('\'', (evdev::Key::KEY_APOSTROPHE, false)),
            // Space is intentionally in both KEY_MAP_LAYOUT (char-to-evdev for text input)
            // and KEY_MAP (Key::Space for key events). Both maps serve different lookup paths.
            (' ', (evdev::Key::KEY_SPACE, false)),

            // Shift + key
            ('A', (evdev::Key::KEY_A, true)),
            ('B', (evdev::Key::KEY_B, true)),
            ('C', (evdev::Key::KEY_C, true)),
            ('D', (evdev::Key::KEY_D, true)),
            ('E', (evdev::Key::KEY_E, true)),
            ('F', (evdev::Key::KEY_F, true)),
            ('G', (evdev::Key::KEY_G, true)),
            ('H', (evdev::Key::KEY_H, true)),
            ('I', (evdev::Key::KEY_I, true)),
            ('J', (evdev::Key::KEY_J, true)),
            ('K', (evdev::Key::KEY_K, true)),
            ('L', (evdev::Key::KEY_L, true)),
            ('M', (evdev::Key::KEY_M, true)),
            ('N', (evdev::Key::KEY_N, true)),
            ('O', (evdev::Key::KEY_O, true)),
            ('P', (evdev::Key::KEY_P, true)),
            ('Q', (evdev::Key::KEY_Q, true)),
            ('R', (evdev::Key::KEY_R, true)),
            ('S', (evdev::Key::KEY_S, true)),
            ('T', (evdev::Key::KEY_T, true)),
            ('U', (evdev::Key::KEY_U, true)),
            ('V', (evdev::Key::KEY_V, true)),
            ('W', (evdev::Key::KEY_W, true)),
            ('X', (evdev::Key::KEY_X, true)),
            ('Y', (evdev::Key::KEY_Y, true)),
            ('Z', (evdev::Key::KEY_Z, true)),
            (')', (evdev::Key::KEY_0, true)),
            ('!', (evdev::Key::KEY_1, true)),
            ('@', (evdev::Key::KEY_2, true)),
            ('#', (evdev::Key::KEY_3, true)),
            ('$', (evdev::Key::KEY_4, true)),
            ('%', (evdev::Key::KEY_5, true)),
            ('^', (evdev::Key::KEY_6, true)),
            ('&', (evdev::Key::KEY_7, true)),
            ('*', (evdev::Key::KEY_8, true)),
            ('(', (evdev::Key::KEY_9, true)),
            ('~', (evdev::Key::KEY_GRAVE, true)),
            ('_', (evdev::Key::KEY_MINUS, true)),
            ('+', (evdev::Key::KEY_EQUAL, true)),
            ('{', (evdev::Key::KEY_LEFTBRACE, true)),
            ('}', (evdev::Key::KEY_RIGHTBRACE, true)),
            ('|', (evdev::Key::KEY_BACKSLASH, true)),
            ('<', (evdev::Key::KEY_COMMA, true)),
            ('>', (evdev::Key::KEY_DOT, true)),
            ('?', (evdev::Key::KEY_SLASH, true)),
            (':', (evdev::Key::KEY_SEMICOLON, true)),
            ('"', (evdev::Key::KEY_APOSTROPHE, true)),
        ]);

    // ((minx, maxx), (miny, maxy))
    pub(super) static ref RESOLUTION: Mutex<((i32, i32), (i32, i32))> = Mutex::new(((0, 0), (0, 0)));
}
